"""fresh_initial_schema

Revision ID: 758988c066b8
Revises: 
Create Date: 2026-03-25 21:52:31.621713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758988c066b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('host', sa.String(length=500), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('agent_card_path', sa.String(length=500), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=False),
    sa.Column('full_history', sa.Boolean(), nullable=False),
    sa.Column('authentication_flag', sa.Boolean(), nullable=False),
    sa.Column('allow_conversation_history', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('mcp_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('installed_from_listing_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('sse_read_timeout', sa.Float(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=False),
    sa.Column('authentication_flag', sa.Boolean(), nullable=False),
    sa.Column('auth_token', sa.String(length=500), nullable=True),
    sa.Column('tool_filter', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tools_installed_from_listing_id'), 'mcp_tools', ['installed_from_listing_id'], unique=False)
    op.create_index(op.f('ix_mcp_tools_owner_id'), 'mcp_tools', ['owner_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('mcp_tool_id', sa.UUID(), nullable=True),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_tool_id'], ['mcp_tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id'),
    sa.UniqueConstraint('mcp_tool_id')
    )
    op.create_index(op.f('ix_marketplace_listings_publisher_id'), 'marketplace_listings', ['publisher_id'], unique=False)
    op.create_foreign_key(
        'fk_mcp_tools_installed_from_listing_id_marketplace_listings',
        'mcp_tools',
        'marketplace_listings',
        ['installed_from_listing_id'],
        ['id'],
        ondelete='SET NULL'
    )
    op.create_table('user_agent_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_user_listing')
    )
    op.create_index(op.f('ix_user_agent_installations_listing_id'), 'user_agent_installations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_user_agent_installations_user_id'), 'user_agent_installations', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('adk_session_id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_adk_session_id'), 'user_sessions', ['adk_session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_adk_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_agent_installations_user_id'), table_name='user_agent_installations')
    op.drop_index(op.f('ix_user_agent_installations_listing_id'), table_name='user_agent_installations')
    op.drop_table('user_agent_installations')
    op.drop_constraint('fk_mcp_tools_installed_from_listing_id_marketplace_listings', 'mcp_tools', type_='foreignkey')
    op.drop_index(op.f('ix_marketplace_listings_publisher_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_mcp_tools_owner_id'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_installed_from_listing_id'), table_name='mcp_tools')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
